version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 296062576962 --region us-east-1 --query authorizationToken --output text`
      - pip config set global.index-url https://aws:$CODEARTIFACT_AUTH_TOKEN@nextwork-296062576962.d.codeartifact.us-east-1.amazonaws.com/pypi/nextwork-devops-cicd/simple/
      - pip install --upgrade pip
      - pip install -r flask-app/requirements.txt

  build:
    commands:
      - echo Build phase — nothing to build for Flask

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no

