---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-east-1:296062576962:generatedTemplate/9af48cd4-1d1d-4f53-8ead-2c4559877dd8"
Parameters:
  KeyName:
    Default: "nextwork-keypair"
    Type: "String"
    Description: "Name of an existing EC2 KeyPair to enable SSH access"
Resources:
  EC2Instance:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::EC2::Instance"
    DeletionPolicy: "Delete"
    Properties:
      Tenancy: "default"
      PrivateIpAddress: "172.31.18.100"
      InstanceInitiatedShutdownBehavior: "stop"
      BlockDeviceMappings:
        - Ebs:
            SnapshotId: "snap-0f9367e47fa8d3648"
            VolumeType: "gp3"
            Iops: 3000
            VolumeSize: 8
            Encrypted: false
            DeleteOnTermination: true
          DeviceName: "/dev/xvda"   # root volume only
      PrivateDnsNameOptions:
        EnableResourceNameDnsARecord: true
        HostnameType: "ip-name"
        EnableResourceNameDnsAAAARecord: false
      IamInstanceProfile: !Ref IAMInstanceProfileCodeartifactnextworkconsumerpolicy
      SubnetId: !Ref EC2Subnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      EbsOptimized: false
      DisableApiTermination: false
      SourceDestCheck: true
      PlacementGroupName: ""
      ImageId: "ami-00ca32bbc84273381"
      InstanceType: "t2.micro"
      Monitoring: false
      Tags:
        - Key: "Name"
          Value: "nextwork-devops-sahithi-aekka"
        - Key: "role"
          Value: "webserver"
      CreditSpecification:
        CPUCredits: "standard"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y ruby wget
          cd /home/ec2-user
          wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          systemctl start codedeploy-agent
          systemctl enable codedeploy-agent

  CodeArtifactRepositoryRepositorynextworknextworkdevopscicd:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      Upstreams:
        - Fn::GetAtt:
            - "CodeArtifactRepositoryRepositorynextworkpypistore"
            - "Name"
      RepositoryName: "nextwork-devops-cicd"
      Description: "Repository for NextWork CI/CD artifacts"
      DomainName:
        Fn::GetAtt:
          - "CodeArtifactDomainDomainnextwork"
          - "Name"

  IAMManagedPolicyPolicyserviceroleCodeBuildCodeConnectionsSourceCredentialsPolicynextworkdevopscicduseast1296062576962:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "CodeBuildCodeConnectionsSourceCredentialsPolicy-nextwork-devops-cicd-us-east-1-296062576962"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - "arn:aws:codeconnections:us-east-1:296062576962:connection/c2388504-9441-43b0-b6c2-c01a10ef69ed"
              - "arn:aws:codeconnections:us-east-1:296062576962:connection/c2388504-9441-43b0-b6c2-c01a10ef69ed"
            Action:
              - "codestar-connections:GetConnectionToken"
              - "codestar-connections:GetConnection"
              - "codeconnections:GetConnectionToken"
              - "codeconnections:GetConnection"
              - "codeconnections:UseConnection"
            Effect: "Allow"
      Users: []

  CodeArtifactDomainDomainnextwork:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Domain"
    DeletionPolicy: "Delete"
    Properties:
      DomainName: "nextwork"

  EC2Subnet:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::EC2::Subnet"
    DeletionPolicy: "Delete"
    Properties:
      MapPublicIpOnLaunch: true
      EnableDns64: false
      VpcId: !Ref EC2VPC
      AvailabilityZoneId: "use1-az4"
      PrivateDnsNameOptionsOnLaunch:
        EnableResourceNameDnsARecord: false
        HostnameType: "ip-name"
        EnableResourceNameDnsAAAARecord: false
      CidrBlock: "172.31.16.0/20"
      Ipv6Native: false
      Tags: []

  EC2SecurityGroup:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::EC2::SecurityGroup"
    DeletionPolicy: "Delete"
    Properties:
      GroupDescription: "launch-wizard-1 created 2025-08-21T19:37:54.852Z"
      GroupName: "launch-wizard-1"
      VpcId: !Ref EC2VPC
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 5000
          ToPort: 5000
      SecurityGroupEgress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"
          FromPort: -1
          ToPort: -1

  IAMRoleCodeartifactnextworkconsumerpolicy:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - Ref: "IAMManagedPolicyPolicycodeartifactnextworkconsumerpolicy"
        - !Ref EC2CodeDeployPolicy
      MaxSessionDuration: 3600
      RoleName: "codeartifact-nextwork-consumer-policy"
      Description: "IAM role for EC2 instances to access CodeArtifact"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"

  EC2CodeDeployPolicy:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "EC2CodeDeployAccessPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogStreams"
              - "logs:DescribeLogGroups"
            Resource: "*"
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
            Resource:
              - !Sub "${S3BucketNextworkdevopscicdsahithiaekka.Arn}/*"
              - !GetAtt S3BucketNextworkdevopscicdsahithiaekka.Arn

  IAMManagedPolicyPolicyserviceroleCodeBuildCloudWatchLogsPolicynextworkdevopscicduseast1:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "CodeBuildCloudWatchLogsPolicy-nextwork-devops-cicd-us-east-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - "arn:aws:logs:us-east-1:296062576962:log-group:/aws/codebuild/nextwork-devops-cicd"
              - "arn:aws:logs:us-east-1:296062576962:log-group:/aws/codebuild/nextwork-devops-cicd:*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: "Allow"
      Users: []

  CodeStarConnectionsConnectionConnectionbdac21d871c644c58f3c0be5ea4c63c2:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeStarConnections::Connection"
    DeletionPolicy: "Delete"
    Properties:
      ConnectionName: "nextwork-devops-cicd"
      ProviderType: "GitHub"
      Tags: []

  CodeDeployApplicationNextworkdevopscicd:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeDeploy::Application"
    DeletionPolicy: "Delete"
    Properties:
      ApplicationName: "nextwork-devops-cicd"
      ComputePlatform: "Server"
  
  CodeBuildProjectNextworkdevopscicd:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeBuild::Project"
    DeletionPolicy: "Delete"
    Properties:
      Name: "nextwork-devops-cicd"
      Description: "CodeBuild project for Nextwork Devops CI/CD"
      ServiceRole: !GetAtt IAMRoleCodebuildnextworkdevopscicdservicerole.Arn
      Source:
        Type: "GITHUB"
        Location: "https://github.com/SahithiAekka/ci-cd-webapp-on-aws"
        BuildSpec: "buildspec.yml"
        GitCloneDepth: 1
      Artifacts:
        Type: "S3"
        Location: !Ref S3BucketNextworkdevopscicdsahithiaekka
        Name: "nextwork-devops-cicd-sahithi-aekka"
        Packaging: "ZIP"
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:7.0"
      Tags: []

  CodeDeployDeploymentGroupNextworkdevopscicd:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeDeploy::DeploymentGroup"
    DeletionPolicy: "Delete"
    Properties:
      ApplicationName: !Ref CodeDeployApplicationNextworkdevopscicd
      DeploymentGroupName: "nextwork-devops-cicd-deployment-group"
      ServiceRoleArn: !GetAtt IAMRoleNextWorkCodeDeployRole.Arn
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Type: "KEY_AND_VALUE"
          Key: "role"
          Value: "webserver"
      AutoScalingGroups: []

      
  IAMManagedPolicyPolicyserviceroleCodeBuildBasePolicynextworkdevopscicduseast1:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "CodeBuildBasePolicy-nextwork-devops-cicd-us-east-1"
      Path: "/service-role/"
      Description: "Policy used in trust relationship with CodeBuild"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - "arn:aws:logs:us-east-1:296062576962:log-group:/aws/codebuild/nextwork-devops-cicd"
              - "arn:aws:logs:us-east-1:296062576962:log-group:/aws/codebuild/nextwork-devops-cicd:*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: "Allow"
          - Resource:
              - "arn:aws:s3:::codepipeline-us-east-1-*"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
            Effect: "Allow"
          - Resource:
              - "arn:aws:s3:::nextwork-devops-cicd-sahithi-aekka"
              - "arn:aws:s3:::nextwork-devops-cicd-sahithi-aekka/*"
            Action:
              - "s3:PutObject"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
            Effect: "Allow"
          - Resource:
              - "arn:aws:codebuild:us-east-1:296062576962:report-group/nextwork-devops-cicd-*"
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
            Effect: "Allow"
      Users: []

  IAMManagedPolicyPolicycodeartifactnextworkconsumerpolicy:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Delete"
    Properties:
      ManagedPolicyName: "codeartifact-nextwork-consumer-policy"
      Path: "/"
      Description: "Policy for EC2 instances to access CodeArtifact"
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "*"
            Action:
              - "codeartifact:GetAuthorizationToken"
              - "codeartifact:GetRepositoryEndpoint"
              - "codeartifact:ReadFromRepository"
            Effect: "Allow"
          - Condition:
              StringEquals:
                sts:AWSServiceName: "codeartifact.amazonaws.com"
            Resource: "*"
            Action: "sts:GetServiceBearerToken"
            Effect: "Allow"
      Users: []

  EC2VPC:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::EC2::VPC"
    DeletionPolicy: "Delete"
    Properties:
      CidrBlock: "172.31.0.0/16"
      EnableDnsSupport: true
      InstanceTenancy: "default"
      EnableDnsHostnames: true
      Tags: []

  IAMRoleNextWorkCodeDeployRole:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
      MaxSessionDuration: 3600
      RoleName: "NextWorkCodeDeployRole"
      Description: "Allows CodeDeploy to call AWS services such as Auto Scaling on your behalf.\nCreated as a part of NextWork's Cl/CD Pipeline series.\n"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "codedeploy.amazonaws.com"
            Sid: ""

  IAMInstanceProfileCodeartifactnextworkconsumerpolicy:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::InstanceProfile"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRoleCodeartifactnextworkconsumerpolicy"
      InstanceProfileName: !Ref IAMRoleCodeartifactnextworkconsumerpolicy

  IAMRoleCodebuildnextworkdevopscicdservicerole:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Delete"
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
        - Ref: "IAMManagedPolicyPolicyserviceroleCodeBuildCloudWatchLogsPolicynextworkdevopscicduseast1"
        - Ref: "IAMManagedPolicyPolicyserviceroleCodeBuildCodeConnectionsSourceCredentialsPolicynextworkdevopscicduseast1296062576962"
        - Ref: "IAMManagedPolicyPolicycodeartifactnextworkconsumerpolicy"
        - Ref: "IAMManagedPolicyPolicyserviceroleCodeBuildBasePolicynextworkdevopscicduseast1"
      MaxSessionDuration: 3600
      RoleName: "codebuild-nextwork-devops-cicd-service-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"

  CodeStarConnectionsConnectionConnection84ea5fc63790467db8ceb66a46e11253:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeStarConnections::Connection"
    DeletionPolicy: "Delete"
    Properties:
      ConnectionName: "nextwork-devops-cicd"
      ProviderType: "GitHub"
      Tags: []

  CodeArtifactRepositoryRepositorynextworkpypistore:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::CodeArtifact::Repository"
    DeletionPolicy: "Delete"
    Properties:
      RepositoryName: "pypi-store"
      Description: "Provides PyPI artifacts from PyPI."
      ExternalConnections:
        - "public:pypi"
      DomainName:
        Fn::GetAtt:
          - "CodeArtifactDomainDomainnextwork"
          - "Name"

  S3BucketNextworkdevopscicdsahithiaekka:
    UpdateReplacePolicy: "Delete"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "nextwork-devops-cicd-sahithi-aekka"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
